In [5]:
np.random.randint(0,50,10)

array([10, 29,  4,  5, 45, 33, 12,  9,  7, 27])

In [19]:
arr[1:3,2:4]

array([[ 6,  7],
       [10, 11]])

In [21]:
arr * arr

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [26]:
np.max(arr ** 2)

121

In [17]:
import numpy as np
arr = np.arange(0,12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])